language: ruby
rvm:
  - 1.9.3

gemfile:
  - ./gemfiles/Gemfile.chef.11.4.4
  - ./gemfiles/Gemfile.chef.11.6.2
  - ./gemfiles/Gemfile.chef.11.8.0
  - ./gemfiles/Gemfile.chef.11.8.2
  - ./gemfiles/Gemfile.chef.11.10.0
  - ./gemfiles/Gemfile.chef.11.10.2
  - ./gemfiles/Gemfile.chef.11.10.4
